version: "3"
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5001
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGODB_URI=mongodb://mongo:27017/collaborative-code-editor
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
